name: bubblebreak-fun
services:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: lightbulbmomentlabs/BubbleBreak
  name: web
  routes:
  - path: /
  source_dir: /
  static_sites:
  - build_command: echo "No build needed"
    catchall_document: index.html
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: lightbulbmomentlabs/BubbleBreak
    name: bubblebreak-static
    output_dir: /
    routes:
    # Clean URL routes for articles
    - path: /articles/take-bubble-break-short-repetitive-breaks-ease-study-stress
      destination: /articles/take-bubble-break-short-repetitive-breaks-ease-study-stress.html
    - path: /articles/beat-exam-anxiety-repetitive-calming-techniques-5-strategies-students
      destination: /articles/beat-exam-anxiety-repetitive-calming-techniques-5-strategies-students.html
    - path: /articles/fidget-to-focus-how-small-repetitive-movements-help-anxiety-classroom
      destination: /articles/fidget-to-focus-how-small-repetitive-movements-help-anxiety-classroom.html
    - path: /articles/why-popping-bubble-wrap-oddly-satisfying-actions-relieve-student-stress
      destination: /articles/why-popping-bubble-wrap-oddly-satisfying-actions-relieve-student-stress.html
    - path: /articles/how-repetitive-actions-reduce-anxiety-students-science-bubble-breaks
      destination: /articles/how-repetitive-actions-reduce-anxiety-students-science-bubble-breaks.html
    - path: /articles/10-repetitive-stress-relief-activities-students
      destination: /articles/10-repetitive-stress-relief-activities-students.html
    - path: /articles/
      destination: /articles/index.html
    - path: /articles
      destination: /articles/index.html
    source_dir: /