name: bubblebreak-app
static_sites:
- name: bubblebreak-static
  source_dir: /
  github:
    repo: lightbulbmomentlabs/BubbleBreak
    branch: main
  build_command: echo "Static site - no build needed"
  output_dir: /
  index_document: index.html
  error_document: index.html

  # Static file serving configuration
  routes:
  - path: /

  # Environment variables for caching
  envs:
  - key: CACHE_STATIC_ASSETS
    value: "true"

  # Custom headers for caching
  headers:
    # CSS and JS files - 1 year cache
    "*.css":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.js":
      Cache-Control: "public, max-age=31536000, immutable"

    # Images - 1 year cache
    "*.jpg":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.jpeg":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.png":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.webp":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.gif":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.svg":
      Cache-Control: "public, max-age=31536000, immutable"
    "*.ico":
      Cache-Control: "public, max-age=604800"

    # HTML files - 1 hour cache
    "*.html":
      Cache-Control: "public, max-age=3600"

    # Security headers
    "*":
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      X-Content-Type-Options: "nosniff"
      Referrer-Policy: "strict-origin-when-cross-origin"